my:
  greeting: Hello Testing
app:
   name: My App
   description: Welcome to ${app.name}
db:
   connection: "{connectionString:'http://_', username:'foo', password:'bar'}"
   host: 129.0.0.1
   port: 7070
management.endpoints.web.exposure.include: "*"
